version: '3'
services:  
  rasa_pl:
    build: 
      context: .
      dockerfile: rasa/Dockerfile  
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    ports:
      - "5005:5005"
      - "5055:5055"
      - "8888:8888"
      - "8090:8090"
    command: sleep infinity

  duckling:
    image: rasa/duckling
    ports:
      - "8010:8000"      